/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaAssistanceRouteImport } from './routes/visa-assistance'
import { Route as UsmleRouteImport } from './routes/usmle'
import { Route as UniversityAdmissionsRouteImport } from './routes/university-admissions'
import { Route as TravelAssistanceRouteImport } from './routes/travel-assistance'
import { Route as ToeflRouteImport } from './routes/toefl'
import { Route as StudentLifeRouteImport } from './routes/student-life'
import { Route as SopWritingRouteImport } from './routes/sop-writing'
import { Route as PteRouteImport } from './routes/pte'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PlabRouteImport } from './routes/plab'
import { Route as OtherProgramsRouteImport } from './routes/other-programs'
import { Route as OetRouteImport } from './routes/oet'
import { Route as NeetRouteImport } from './routes/neet'
import { Route as MbbsToMdRouteImport } from './routes/mbbs-to-md'
import { Route as IndianUniversitiesRouteImport } from './routes/indian-universities'
import { Route as IeltsRouteImport } from './routes/ielts'
import { Route as GreRouteImport } from './routes/gre'
import { Route as EducationLoanRouteImport } from './routes/education-loan'
import { Route as DuolingoRouteImport } from './routes/duolingo'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CareerCounselingRouteImport } from './routes/career-counseling'
import { Route as BlogsEventsRouteImport } from './routes/blogs-events'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VisaAssistanceRoute = VisaAssistanceRouteImport.update({
  id: '/visa-assistance',
  path: '/visa-assistance',
  getParentRoute: () => rootRouteImport,
} as any)
const UsmleRoute = UsmleRouteImport.update({
  id: '/usmle',
  path: '/usmle',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityAdmissionsRoute = UniversityAdmissionsRouteImport.update({
  id: '/university-admissions',
  path: '/university-admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelAssistanceRoute = TravelAssistanceRouteImport.update({
  id: '/travel-assistance',
  path: '/travel-assistance',
  getParentRoute: () => rootRouteImport,
} as any)
const ToeflRoute = ToeflRouteImport.update({
  id: '/toefl',
  path: '/toefl',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLifeRoute = StudentLifeRouteImport.update({
  id: '/student-life',
  path: '/student-life',
  getParentRoute: () => rootRouteImport,
} as any)
const SopWritingRoute = SopWritingRouteImport.update({
  id: '/sop-writing',
  path: '/sop-writing',
  getParentRoute: () => rootRouteImport,
} as any)
const PteRoute = PteRouteImport.update({
  id: '/pte',
  path: '/pte',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlabRoute = PlabRouteImport.update({
  id: '/plab',
  path: '/plab',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherProgramsRoute = OtherProgramsRouteImport.update({
  id: '/other-programs',
  path: '/other-programs',
  getParentRoute: () => rootRouteImport,
} as any)
const OetRoute = OetRouteImport.update({
  id: '/oet',
  path: '/oet',
  getParentRoute: () => rootRouteImport,
} as any)
const NeetRoute = NeetRouteImport.update({
  id: '/neet',
  path: '/neet',
  getParentRoute: () => rootRouteImport,
} as any)
const MbbsToMdRoute = MbbsToMdRouteImport.update({
  id: '/mbbs-to-md',
  path: '/mbbs-to-md',
  getParentRoute: () => rootRouteImport,
} as any)
const IndianUniversitiesRoute = IndianUniversitiesRouteImport.update({
  id: '/indian-universities',
  path: '/indian-universities',
  getParentRoute: () => rootRouteImport,
} as any)
const IeltsRoute = IeltsRouteImport.update({
  id: '/ielts',
  path: '/ielts',
  getParentRoute: () => rootRouteImport,
} as any)
const GreRoute = GreRouteImport.update({
  id: '/gre',
  path: '/gre',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationLoanRoute = EducationLoanRouteImport.update({
  id: '/education-loan',
  path: '/education-loan',
  getParentRoute: () => rootRouteImport,
} as any)
const DuolingoRoute = DuolingoRouteImport.update({
  id: '/duolingo',
  path: '/duolingo',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCounselingRoute = CareerCounselingRouteImport.update({
  id: '/career-counseling',
  path: '/career-counseling',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsEventsRoute = BlogsEventsRouteImport.update({
  id: '/blogs-events',
  path: '/blogs-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admissions': typeof AdmissionsRoute
  '/blogs-events': typeof BlogsEventsRoute
  '/career-counseling': typeof CareerCounselingRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/duolingo': typeof DuolingoRoute
  '/education-loan': typeof EducationLoanRoute
  '/gre': typeof GreRoute
  '/ielts': typeof IeltsRoute
  '/indian-universities': typeof IndianUniversitiesRoute
  '/mbbs-to-md': typeof MbbsToMdRoute
  '/neet': typeof NeetRoute
  '/oet': typeof OetRoute
  '/other-programs': typeof OtherProgramsRoute
  '/plab': typeof PlabRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/pte': typeof PteRoute
  '/sop-writing': typeof SopWritingRoute
  '/student-life': typeof StudentLifeRoute
  '/toefl': typeof ToeflRoute
  '/travel-assistance': typeof TravelAssistanceRoute
  '/university-admissions': typeof UniversityAdmissionsRoute
  '/usmle': typeof UsmleRoute
  '/visa-assistance': typeof VisaAssistanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admissions': typeof AdmissionsRoute
  '/blogs-events': typeof BlogsEventsRoute
  '/career-counseling': typeof CareerCounselingRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/duolingo': typeof DuolingoRoute
  '/education-loan': typeof EducationLoanRoute
  '/gre': typeof GreRoute
  '/ielts': typeof IeltsRoute
  '/indian-universities': typeof IndianUniversitiesRoute
  '/mbbs-to-md': typeof MbbsToMdRoute
  '/neet': typeof NeetRoute
  '/oet': typeof OetRoute
  '/other-programs': typeof OtherProgramsRoute
  '/plab': typeof PlabRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/pte': typeof PteRoute
  '/sop-writing': typeof SopWritingRoute
  '/student-life': typeof StudentLifeRoute
  '/toefl': typeof ToeflRoute
  '/travel-assistance': typeof TravelAssistanceRoute
  '/university-admissions': typeof UniversityAdmissionsRoute
  '/usmle': typeof UsmleRoute
  '/visa-assistance': typeof VisaAssistanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admissions': typeof AdmissionsRoute
  '/blogs-events': typeof BlogsEventsRoute
  '/career-counseling': typeof CareerCounselingRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/duolingo': typeof DuolingoRoute
  '/education-loan': typeof EducationLoanRoute
  '/gre': typeof GreRoute
  '/ielts': typeof IeltsRoute
  '/indian-universities': typeof IndianUniversitiesRoute
  '/mbbs-to-md': typeof MbbsToMdRoute
  '/neet': typeof NeetRoute
  '/oet': typeof OetRoute
  '/other-programs': typeof OtherProgramsRoute
  '/plab': typeof PlabRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/pte': typeof PteRoute
  '/sop-writing': typeof SopWritingRoute
  '/student-life': typeof StudentLifeRoute
  '/toefl': typeof ToeflRoute
  '/travel-assistance': typeof TravelAssistanceRoute
  '/university-admissions': typeof UniversityAdmissionsRoute
  '/usmle': typeof UsmleRoute
  '/visa-assistance': typeof VisaAssistanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admissions'
    | '/blogs-events'
    | '/career-counseling'
    | '/careers'
    | '/contact'
    | '/courses'
    | '/duolingo'
    | '/education-loan'
    | '/gre'
    | '/ielts'
    | '/indian-universities'
    | '/mbbs-to-md'
    | '/neet'
    | '/oet'
    | '/other-programs'
    | '/plab'
    | '/privacy-policy'
    | '/pte'
    | '/sop-writing'
    | '/student-life'
    | '/toefl'
    | '/travel-assistance'
    | '/university-admissions'
    | '/usmle'
    | '/visa-assistance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admissions'
    | '/blogs-events'
    | '/career-counseling'
    | '/careers'
    | '/contact'
    | '/courses'
    | '/duolingo'
    | '/education-loan'
    | '/gre'
    | '/ielts'
    | '/indian-universities'
    | '/mbbs-to-md'
    | '/neet'
    | '/oet'
    | '/other-programs'
    | '/plab'
    | '/privacy-policy'
    | '/pte'
    | '/sop-writing'
    | '/student-life'
    | '/toefl'
    | '/travel-assistance'
    | '/university-admissions'
    | '/usmle'
    | '/visa-assistance'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admissions'
    | '/blogs-events'
    | '/career-counseling'
    | '/careers'
    | '/contact'
    | '/courses'
    | '/duolingo'
    | '/education-loan'
    | '/gre'
    | '/ielts'
    | '/indian-universities'
    | '/mbbs-to-md'
    | '/neet'
    | '/oet'
    | '/other-programs'
    | '/plab'
    | '/privacy-policy'
    | '/pte'
    | '/sop-writing'
    | '/student-life'
    | '/toefl'
    | '/travel-assistance'
    | '/university-admissions'
    | '/usmle'
    | '/visa-assistance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdmissionsRoute: typeof AdmissionsRoute
  BlogsEventsRoute: typeof BlogsEventsRoute
  CareerCounselingRoute: typeof CareerCounselingRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  DuolingoRoute: typeof DuolingoRoute
  EducationLoanRoute: typeof EducationLoanRoute
  GreRoute: typeof GreRoute
  IeltsRoute: typeof IeltsRoute
  IndianUniversitiesRoute: typeof IndianUniversitiesRoute
  MbbsToMdRoute: typeof MbbsToMdRoute
  NeetRoute: typeof NeetRoute
  OetRoute: typeof OetRoute
  OtherProgramsRoute: typeof OtherProgramsRoute
  PlabRoute: typeof PlabRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PteRoute: typeof PteRoute
  SopWritingRoute: typeof SopWritingRoute
  StudentLifeRoute: typeof StudentLifeRoute
  ToeflRoute: typeof ToeflRoute
  TravelAssistanceRoute: typeof TravelAssistanceRoute
  UniversityAdmissionsRoute: typeof UniversityAdmissionsRoute
  UsmleRoute: typeof UsmleRoute
  VisaAssistanceRoute: typeof VisaAssistanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visa-assistance': {
      id: '/visa-assistance'
      path: '/visa-assistance'
      fullPath: '/visa-assistance'
      preLoaderRoute: typeof VisaAssistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usmle': {
      id: '/usmle'
      path: '/usmle'
      fullPath: '/usmle'
      preLoaderRoute: typeof UsmleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university-admissions': {
      id: '/university-admissions'
      path: '/university-admissions'
      fullPath: '/university-admissions'
      preLoaderRoute: typeof UniversityAdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-assistance': {
      id: '/travel-assistance'
      path: '/travel-assistance'
      fullPath: '/travel-assistance'
      preLoaderRoute: typeof TravelAssistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toefl': {
      id: '/toefl'
      path: '/toefl'
      fullPath: '/toefl'
      preLoaderRoute: typeof ToeflRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life': {
      id: '/student-life'
      path: '/student-life'
      fullPath: '/student-life'
      preLoaderRoute: typeof StudentLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sop-writing': {
      id: '/sop-writing'
      path: '/sop-writing'
      fullPath: '/sop-writing'
      preLoaderRoute: typeof SopWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pte': {
      id: '/pte'
      path: '/pte'
      fullPath: '/pte'
      preLoaderRoute: typeof PteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plab': {
      id: '/plab'
      path: '/plab'
      fullPath: '/plab'
      preLoaderRoute: typeof PlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other-programs': {
      id: '/other-programs'
      path: '/other-programs'
      fullPath: '/other-programs'
      preLoaderRoute: typeof OtherProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oet': {
      id: '/oet'
      path: '/oet'
      fullPath: '/oet'
      preLoaderRoute: typeof OetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neet': {
      id: '/neet'
      path: '/neet'
      fullPath: '/neet'
      preLoaderRoute: typeof NeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mbbs-to-md': {
      id: '/mbbs-to-md'
      path: '/mbbs-to-md'
      fullPath: '/mbbs-to-md'
      preLoaderRoute: typeof MbbsToMdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indian-universities': {
      id: '/indian-universities'
      path: '/indian-universities'
      fullPath: '/indian-universities'
      preLoaderRoute: typeof IndianUniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ielts': {
      id: '/ielts'
      path: '/ielts'
      fullPath: '/ielts'
      preLoaderRoute: typeof IeltsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gre': {
      id: '/gre'
      path: '/gre'
      fullPath: '/gre'
      preLoaderRoute: typeof GreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education-loan': {
      id: '/education-loan'
      path: '/education-loan'
      fullPath: '/education-loan'
      preLoaderRoute: typeof EducationLoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duolingo': {
      id: '/duolingo'
      path: '/duolingo'
      fullPath: '/duolingo'
      preLoaderRoute: typeof DuolingoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-counseling': {
      id: '/career-counseling'
      path: '/career-counseling'
      fullPath: '/career-counseling'
      preLoaderRoute: typeof CareerCounselingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs-events': {
      id: '/blogs-events'
      path: '/blogs-events'
      fullPath: '/blogs-events'
      preLoaderRoute: typeof BlogsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdmissionsRoute: AdmissionsRoute,
  BlogsEventsRoute: BlogsEventsRoute,
  CareerCounselingRoute: CareerCounselingRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  DuolingoRoute: DuolingoRoute,
  EducationLoanRoute: EducationLoanRoute,
  GreRoute: GreRoute,
  IeltsRoute: IeltsRoute,
  IndianUniversitiesRoute: IndianUniversitiesRoute,
  MbbsToMdRoute: MbbsToMdRoute,
  NeetRoute: NeetRoute,
  OetRoute: OetRoute,
  OtherProgramsRoute: OtherProgramsRoute,
  PlabRoute: PlabRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PteRoute: PteRoute,
  SopWritingRoute: SopWritingRoute,
  StudentLifeRoute: StudentLifeRoute,
  ToeflRoute: ToeflRoute,
  TravelAssistanceRoute: TravelAssistanceRoute,
  UniversityAdmissionsRoute: UniversityAdmissionsRoute,
  UsmleRoute: UsmleRoute,
  VisaAssistanceRoute: VisaAssistanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
